# Generated by Django 2.1.7 on 2022-06-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_date_buyer_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='date',
            field=models.DateField(),
        ),
    ]
